# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
- env:
    - CGO_ENABLED=0
  goarch:
    - amd64
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
brews:
  -
    name: powerline-go
    github:
      owner: cyberbliss
      name: homebrew-tap
    commit_author:
      name: cyberbliss
      email: stephen.judd@gmail.com
    folder: Formula
    homepage: "https://github.com/cyberbliss/powerline-go"
    description: "A beautiful and useful low-latency prompt for your shell, written in go"
    test: |
      system "#{bin}/powerline-go --version"
    install: |
      bin.install "powerline-go"
    caveats: "You'll need to update your .zshrc/.bashrc/.profile. Deets in the readme: https://github.com/cyberbliss/powerline-go#bash"